# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: 'backend' # Here the path to the folder where package-lock.json is located.

    steps:
    - uses: actions/checkout@v4

    - name: Node installation
      uses: actions/setup-node@v4
      with:
        node-version: 22
    
    - name: Create .env file
      run: |
        touch .env
        echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
        echo "COMMUNICATION_SERVICES_CONNECTION_STRING=${{ secrets.COMMUNICATION_SERVICES_CONNECTION_STRING }}" >> .env
        echo "EMAIL_SENDER=${{ secrets.EMAIL_SENDER }}" >> .env
        echo "FLASK_API_URL=${{ secrets.FLASK_API_URL }}" >> .env
        echo "FRONT_END_URL=${{ secrets.FRONT_END_URL }}" >> .env
        echo "JWT_LIFETIME=${{ secrets.JWT_LIFETIME }}" >> .env
        echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
        echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env
        echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "STRIPE_ENDPOINT_SECRET=${{ secrets.STRIPE_ENDPOINT_SECRET }}" >> .env
        echo "STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}" >> .env
        echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env
        
    - name: Install dependencies
      run: npm install

    - name: Build
      run: |
        npm start
        echo "Build completed"
            
